unification/code cleanup

diff --git a/datastore/eternus/mkfs b/datastore/eternus/mkfs
--- a/datastore/eternus/mkfs
+++ b/datastore/eternus/mkfs
@@ -1,28 +1,21 @@
 #!/bin/bash
-#exec &> >(tee -a "/tmp/eternus-mkfs.log")
 
-# -------------------------------------------------------------------------- #
-# Copyright 2014, Laurent Grawet <dev@grawet.be>                             #
-#                                                                            #
-# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
-# not use this file except in compliance with the License. You may obtain    #
-# a copy of the License at                                                   #
-#                                                                            #
-# http://www.apache.org/licenses/LICENSE-2.0                                 #
-#                                                                            #
-# Unless required by applicable law or agreed to in writing, software        #
-# distributed under the License is distributed on an "AS IS" BASIS,          #
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
-# See the License for the specific language governing permissions and        #
-# limitations under the License.                                             #
-#--------------------------------------------------------------------------- #
+# OpenNebula driver for Fujitsu Eternus DX series
+# https://github.com/deepthinkag/OpenNebula-addon-eternus/
+# <fhe@deepthink.ag>
 
-###############################################################################
-# This script is used to create a VM image (SRC) of size (SIZE) and formatted
-# as (FS)
-###############################################################################
+#PHASE: INIT
 
-# -------- Set up the environment to source common tools & conf ------------
+#mkfs: creates a new empty image in the datastore
+#ARGUMENTS: datastore_image_dump image_id
+#datastore_image_dump is an XML dump of the driver action encoded in Base 64.
+#image_source is the image source which will be later sent to the transfer manager.
+
+set -u
+
+[[ $# != 2 ]] || exit 1
+DRV_ACTION="${1}"
+ID="${2}"
 
 if [ -z "${ONE_LOCATION}" ]; then
     LIB_LOCATION=/usr/lib/one
@@ -30,58 +23,30 @@ else
     LIB_LOCATION=$ONE_LOCATION/lib
 fi
 
-. $LIB_LOCATION/sh/scripts_common.sh
-
-DRIVER_PATH=$(dirname $0)
-source ${DRIVER_PATH}/../libfs.sh
-source ${DRIVER_PATH}/scripts_eternus.sh
+DRV_PATH=$(dirname  "$0")
+DRV_TASK=$(basename "$0")
 
 
-DRV_ACTION=$1
-ID=$2
+# source opennebula tools and eternus scripts
+for lib in ${LIB_LOCATION}/sh/scripts_common.sh ${DRV_PATH}/../libfs.sh ${DRV_PATH}/scripts_eternus.sh; do
+    bash -eun "$lib" && source "$lib" || { echo "Error: failed to set up driver"; exit 1; }
+done
 
-if [ "$ID" -eq 120 ]; then
-    echo "$DRV_ACTION" > /tmp/eternus-mkfs.params
+# parse XML Data from DRV_ACTION
+get_xpath_info
+
+if [[ $DEBUG = "y" ]]; then
+    echo "$DRV_ACTION" > /var/tmp/one/eternus-"${DRV_TASK}".params
+    exec &> >(tee -a /var/tmp/one/eternus-"${DRV_TASK}.log")
 fi
 
-XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"
-
-unset i XPATH_ELEMENTS
-
-while IFS= read -r -d '' element; do
-    XPATH_ELEMENTS[i++]="$element"
-done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
-                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/RESTRICTED_DIRS \
-                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SAFE_DIRS \
-                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/UMASK \
-                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
-                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/ARRAY_MGMTIP \
-                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/ARRAY_POOL_NAME \
-                    /DS_DRIVER_ACTION_DATA/IMAGE/FSTYPE \
-                    /DS_DRIVER_ACTION_DATA/IMAGE/SIZE)
-
-#                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BASE_IQN \
-#CLUSTER="${XPATH_ELEMENTS[17]:-$CLUSTER}"
-#BASE_IQN="${XPATH_ELEMENTS[18]:-$BASE_IQN}"
-
-#set -x
-BASE_PATH="${XPATH_ELEMENTS[0]}"
-RESTRICTED_DIRS="${XPATH_ELEMENTS[1]}"
-SAFE_DIRS="${XPATH_ELEMENTS[2]}"
-UMASK="${XPATH_ELEMENTS[3]}"
-BRIDGE_LIST="${XPATH_ELEMENTS[4]:-$BRIDGE_LIST}"
-ARRAY_MGMTIP="${XPATH_ELEMENTS[5]}"
-ARRAY_POOL_NAME="${XPATH_ELEMENTS[6]}"
-FSTYPE="${XPATH_ELEMENTS[7]}"
-SIZE="${XPATH_ELEMENTS[8]:-0}"
-
-
-DST_HOST=`get_destination_host $ID`
-
-# -------- Start actions ------------
+#PHASE: PREP
+DST_HOST=$( get_destination_host "$ID" )
 
 set_up_datastore "$BASE_PATH" "$RESTRICTED_DIRS" "$SAFE_DIRS" "$UMASK"
 
+
+#PHASE: RUN
 VVOL_NAME="one-${ID}"
 
 VVOL_CREATE=$( eternus_ssh_monitor_and_log "${ARRAY_MGMTIP}" \
@@ -91,9 +56,15 @@ VVOL_UID=$( eternus_get_vvol_uid "${VVOL_NAME}" "${ARRAY_MGMTIP}" )
 MAP_NAME="3${VVOL_UID}"
 DEV="/dev/mapper/${MAP_NAME}"
 
+#PHASE: POST
+#RETURNS: image_source size
 
+echo "$DEV" "$SIZE"
+
+
+# is this useless code? since no code is run if type is other than those 3...
 # ------------ Image to save_as disk, no need to create a FS ------------
-
-if [ "$FSTYPE" = "save_as" ] || [ "$FSTYPE" = "raw" ] || [ "$FSTYPE" = "" ]; then
-    exit 0
-fi
+#
+#if [ "$FSTYPE" = "save_as" ] || [ "$FSTYPE" = "raw" ] || [ "$FSTYPE" = "" ]; then
+#    exit 0
+#fi
diff --git a/datastore/eternus/monitor b/datastore/eternus/monitor
--- a/datastore/eternus/monitor
+++ b/datastore/eternus/monitor
@@ -1,12 +1,22 @@
 #!/bin/bash
 
-###############################################################################
-# This script is used to monitor the free and used space of a datastore
-###############################################################################
-# for Fujitsu Eternus DX series
+# OpenNebula driver for Fujitsu Eternus DX series
+# https://github.com/deepthinkag/OpenNebula-addon-eternus/
 # <fhe@deepthink.ag>
 
+#PHASE: INIT
+#monitor: monitors a datastore
+#ARGUMENTS: datastore_action_dump image_id
+#datastore_image_dump is an XML dump of the driver action encoded in Base 64. See a decoded example.
+#monitor data The monitoring information of the datastore, namely “USED_MB=…\nTOTAL_MB=…\nFREE_MB=…” which are respectively the used size of the datastore in MB, the total capacity of the datastore in MB and the available space in the datastore in MB.
+
 # -------- Set up the environment to source common tools & conf ------------
+
+set -u
+
+[[ $# != 2 ]] || exit 1
+DRV_ACTION="${1}"
+ID="${2}"
 
 if [ -z "${ONE_LOCATION}" ]; then
     LIB_LOCATION=/usr/lib/one
@@ -14,40 +24,19 @@ else
     LIB_LOCATION=$ONE_LOCATION/lib
 fi
 
-. $LIB_LOCATION/sh/scripts_common.sh
+DRV_PATH=$(dirname  "$0")
+DRV_TASK=$(basename "$0")
 
-DRIVER_PATH=$(dirname $0)
-source ${DRIVER_PATH}/../libfs.sh
 
-# -------- Get datastore arguments from OpenNebula core ------------
+# source opennebula tools and eternus scripts
+for lib in ${LIB_LOCATION}/sh/scripts_common.sh ${DRV_PATH}/../libfs.sh ${DRV_PATH}/scripts_eternus.sh; do
+    bash -eun "$lib" && source "$lib" || { echo "Error: failed to set up driver"; exit 1; }
+done
 
-DRV_ACTION=$1
-ID=$2
+# library
+get_xpath_info
 
-XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"
-
-unset i j XPATH_ELEMENTS
-
-while IFS= read -r -d '' element; do
-    XPATH_ELEMENTS[i++]="$element"
-done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST   \
-                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/ARRAY_NAME    \
-                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/ARRAY_POOL_NAME    \
-                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/ARRAY_MGMTIP)
-# ARRAY_NAME name of the eternus storage under THIS datastore
-# ARRAY_MGMTIP management ip address of the eternus storage under THIS datastore
-# ARRAY_POOL_NAME the thin provisioning pool to use for this LUN
-# we assume one initiator group
-# the driver does not handle any group operation, you need already
-# attached and multipathed storage connectivity
-
-unset i
-
-BRIDGE_LIST="${XPATH_ELEMENTS[i++]}"
-ARRAY_NAME="${XPATH_ELEMENTS[i++]}"
-ARRAY_POOL_NAME="${XPATH_ELEMENTS[i++]}"
-ARRAY_MGMTIP="${XPATH_ELEMENTS[i++]}"
-
+#PHASE: PREP
 HOST=$( get_destination_host )
 # point at system with network access to mgmt ip *AND .ssh/config set up*
 
@@ -55,6 +44,8 @@ if [ -z "$HOST" ]; then
     error_message "Datastore template missing 'BRIDGE_LIST' attribute."
     exit 1
 fi
+
+#PHASE: RUN
 
 # ------------ Compute datastore usage -------------
 # complete output: see doc/commands-overview.md
@@ -71,7 +62,8 @@ EOF
 MONITOR_DATA=$(ssh_monitor_and_log "${HOST}" "${MONITOR_SCRIPT}")
 MONITOR_STATUS=$?
 
-
+#PHASE: POST
+#RETURNS: monitor data
 # TODO: postcond: validate generated monitor result
 # if MONITOR_DATA matches MONITOR_DATA_REGEX ]; then
 if [ $MONITOR_STATUS = 0 ]; then
